apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vote-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - voting-staging
      - voting-prod

  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - voting-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s