apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-exporter-config
  namespace: monitoring
spec:
  encryptedData:
    postgres_exporter.yml: AgA4b8cr860HRlySLktGRsATtxohnytg8AZdT84RQ4KZyEqlWvXNwxbgIvE/AoRID8wyuGZPgTM1JPh1bXbXFdK9qZOP0yXLd13BztGy2TxsUM1kS08CZK8qk2+O3/lacVxE4ZUycpG9pma2smVSdu4ro78hC5CeUtO3RZgoOR1lfIVNpX7mI/gHXcyA0+Am5G/36rDxqzUB7wtsQiaHugurtkvj3Gdxcoit5tg5WfnCA5C0lixjTaiASXKvZrvllqfvmFaUW0VRi+TBO+EFDzvRu8Ht1Y9XWBl5B4t04CSNwyhKd+jiosY9Z3oHu8Sc/iBxTpVyzqd4s3b55wyIRhpDSbFqbj0QSTqRbxO7CjXWW0IX6urNjze7M81WwmHWTT4lr9bWRXDoDdBt+fh6usR9z3KYz7MkfBZBYq02lbsj6ViO7iH1zDYnT6KFaBLp/Oc1sWbM7upbpyj9nCvH2nVhLrL+b0YZ8ATI9wMopU9/4oOYrSE6egOds3bu8a9Y+Rc5WLfO01ly8SgFz1MSOqxbVS5VmNxWS78Hox2KIl8RtCKBgJOQmqXBPrSynsw4rVzAKAcsepPMjK7bCF8IA4tfHl3xGJaJUln/obgAbydC4rRPvDUrsYiSWI+GF/2OsREoYvNCVrmaq78p+xzLJnYor2hKSG3CJ4QD71yFum76jrfc4EQZluM5wDL+3dQ4VMMGeCdWMDCxjgReFhgj0pWQ1rsXAP7vpWO2Lq/zfmrNOJ2XYhOYOdbomYGD880BixXOn+s8ScEduk0tqQHYCgp1Pxdh0FxJ7FgbJdZBpTj5FGPI2/4zY+VnaKyHVyI2loOWzr074Gc7J1GfXi1z2hNx6vbq7uFLJXUv++pPEmVw+T9d3Y97W/ttVbChyaF/U3OYEtcSXDAARAySeHtkdRZxTSHWXY6zVeHNUHCNHs5k6FIDjCIWkIaYcNmazAZ5tNbGnjTPi1yySrtXu+5W6QYeT0Kb9y91TSx2kDDc2aRcwOe/OE+L8gFANkNYQ+ZK6QGQxqvNploaC7Yf3qsT/f/PDpIaSRVIL5VX4ui7yX1awqvH7MfJC5RXGbVofxHEmrvWsjrzaTs31YWn/hDaAopWdW5p
  template:
    metadata:
      creationTimestamp: null
      name: postgres-exporter-config
      namespace: monitoring
    type: Opaque