apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- secrets


images:

- name: houssemdhahri93/voting-result
  newName: houssemdhahri93/voting-result
  newTag: v1.0.0

- name: houssemdhahri93/voting-vote
  newName: houssemdhahri93/voting-vote
  newTag: v1.0.0
  
- name: houssemdhahri93/voting-worker
  newName: houssemdhahri93/voting-worker
  newTag: v1.0.0
