apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: local-pvc-exporter
  namespace: monitoring
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: local-pvc-exporter

  namespaceSelector:
    matchNames:
      - monitoring

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s