apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: result-secret
  namespace: voting-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCMXl5JxNr43vdhiwQ0ppqLtNBm2+GdpW9Rx0BHahYhDhcMpt0QE2Y677vudjTSwHM6/ZVEfC9mb8ueyPaN6viE5liM90X9C2gjm2yN8o4eQTPhKtbu+e0zq2crx5qQPtksxm8Z06tC3ed+VhwikIzQ9O0Wn9mQ+u+bbUrzpLMOCL3cG1QJlLS3MHMGqzvoB5NaZ9d5wr2GElJnCuPMx1cpj6hNETF9qf6Yu5qrZp+/kE/uv9mJLMoPf4tX0C8wnQPg1Vewtw/Ep9jPZh7NyIX+ld6ZesU2FXY3kdkpywT0KYdpCJuYUoEoNhZEzwaO1vu5aagPCA5s1fuioulyyYkNmvS96ncPeLSfePXOYKh7rT0G7eMVrfF2zVaXpg6mrYWIU4h50RpiGrTyNCxmxes98xCjrlvwADA9+N2t8L1SaXMDQoJ2Pb5TzzS/qWloeT0JSbJLyMSwrFKx/zsA3SQ5blxDmA9GacMFvTQ1vqnVus1PZJdpjXnqZdTzIOK0/J7IafuzH44J3ydmKUTyoa3Ir7L2Nbb8A3it7InzV08xEyqNDamjQimBc8IT6rK3GNAdZcyO7nRXuRq5nMYIYLZtl8D5gi/ijLOOI7TIZzPeVTPJRnn9p8f2e3a8HKWgw5yk0/JRiJ8c+LR8JwvcxxEA2Tm6+5TStSWWDWdSZH3fudpi3TjWQbU91UT2woXoJVcjHvLUpsJ9hNrb
    # houssem123
  
  template:
    metadata:
      creationTimestamp: null
      name: result-secret
      namespace: voting-prod
    type: Opaque