apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: voting-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCzdpqvBuHU3IGfYbveglKtqsrW/OayXIUqb2z9fCVpV7P/o+EW2p9CRRwoCP3QhOalGqdjM8LiJsqZOQBRR1Hq5AlWQzZuNdrsMyuQh8AY0n5QunmkV8V0bQsN+57E6YF7qDrjGxrjGkK4+fPl3m07WAGKmHxTAXX5vcgxHmRvPh00dW7DyZCizMuxi7ALcUSzw1yYrKGCX19x1OACuUaJiBe5b4rVOSg4rMmtbW+6x3+Zo/AUBZ4rztXAwivbRtuhItbe1KrehXGGJUDLRID/iaPd6zwDlMAMOOs2Qn3rwRCaVkdD8IYxk1aWqcUrdYSnE0Gjlgsj0KLMlGuo7SSFuqWdDRwKVuLHQcTP1i9UlY+JXf/2V+yNE1WojXkoCLCEFZKcrLsG2c89xidFAvXWJvpAHK6euHkZco8FGBUJklnFNdwoEjW6NmKJYc70OVQ25R0LmoTXd/3/taq3CCnpIVZNJtBQTTeaIIxt08bGfkDWCIqbC/eQXaFO+3ALlapmXgFH2l3vGCsaWm9seOuGKF+vxFoRqRnx2Un3NR6fO8Bxe85VhTYyXwltd0x8rDTh30OUA5M61ixAHsZMNO2FFvwG/Q+UhXsB25SXdCfttAsE9JLiPZdJ9AndM3hwrBeStAcPeWirwbdZKTwKEio83XYwEV6eIRiY8yTut9dZKk8kDVx4rYRarmepBPnqOKNfHR0RqgVaCdTr
    # houssem123
  
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: voting-prod
    type: Opaque