apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: result-secret
  namespace: voting-prod

spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBfKmVyLQv7bnGemfX6tk3gt44hGsCRjIHPyl/X43dKt/AWtRd5TleAFJ2D/HV2yG5k4s1PV2AJudYH6HNy1q8FNzlp1WrlPsT6ZUvwR7J/qJhu4LoDzbcYA9gAeK4OQtvCH8otqgXZTLkKtWMsX/CCtTg20VAYlqaPxsNAUoLOhFd8G9Bx2Sex44pjeuLt3dsOpvr/I3jvf6yZINnEcxNO2EwJxMRXwg6+3SjU5WlUI2bV3kCCubztmeibuUF93RBXhmvAT4RePqU9+7kvxTEWatb63LD8XM6yurtmWFWWmyF2z79oQd9tG2rrgDuxcU6T7FXg5qXTqVqJArx4xzJigYRWF5k7pEhIS2Bs5OnF++qiiqwdalyPnGu7u8GpjOCuYb7Fc6PgUzOYmPbqteTEqrLvfTiwMLvk+28w9FRQfyw1A6VyxgSaJf9S98FT3WV+L0+9e/JDu6l4TEWIDcHz4CcVhhNh0xn+LIMK1yNItYgpzmn3n8mD7z6LQkq2IbW3i081B+GI1qzE1PKnFdFHjjFUdc7p4+VtfJxjzccx2AJNcpfJ0lHMaDUVK/v92xnqS7/ZXG7BfsNuVKeORGJQwpcqF2oisV6KVwDm4hnh9zwY/ZrSefRbTD4AyIXiDt1/6otPA2ArQhtxsdOTG+bTaOcSKtXuuVIdzj1R47Q2v/eQlVGij3TDHuH4r5s5Em4nZcbhXTXD6vAwUzw=
  
  # "houssem-prod"
  
  template:
    metadata:
      creationTimestamp: null
      name: result-secret
      namespace: voting-prod
    type: Opaque