apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: worker-secret
  namespace: voting-prod
spec:
  encryptedData:
    DB_PASSWORD: AgBp5K94ydgRMZNujxVERq8qiYC0l5LXm7hz8YjnJlt72pBeIXbD2NRRRlXj6olgBS0gxhDypgsVUgSiWy224sHI9e8DAN+k6d7RB5R2sn+yBxavAdoxdWXTo9Sa3rhjKTaPrgQqFFImvOqK9S2VEBDRDqpZ1/vGZq70hyJvnVI7NCkAB7XIGQJVcMdrx5aD1m9BXiVuKEqRxCDdQ7uyTXuhlqrewbcmPGwOiVueMmL+4/NkJyquUbz9rRbcg3akBu6HNvA99dL4HJAhvRC3F1Qc/YFasG1CIFDZmXGfvAHvRFbcer1YZyrbDezv3rKxVYVNLzgmp/vZi6mCfmTZ2Fzu6aWxHkPMo152M7+MaedH6/9ueD4o2+rKuxc4p2kuplprCjLJGAxTnjGuGaDrCfkCSNrgw6lXLLCU8dGI0oglToay1DDd4Fb41KNcxbItHw51tzfj2yWNWKdCq3YQExcOKhVcTsJZCJ3IYCl4jquni+jcp1HyYeNONGxH8794eUYB/qyGm81CVbIKOK6b53cQMc6bdFKFfFsSi90h1+ATiawXh3ZDhy0TubvM0k9KpQu0L3Ns+6BhnCT/GqycAMHGn5vPIC5/L2Th8E4tKbIWqmgl2ZTm24tnoz2a5/OYZuL7P2z22ig5ROzU7rW7s+bzPTl38ntzj1J2XurblTTLAlQw1TrEcwap0cvGQuZJ1JdYo4l4SGai2dhX
    # houssem123
  
  template:
    metadata:
      creationTimestamp: null
      name: worker-secret
      namespace: voting-prod
    type: Opaque