apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: voting-prod

spec:
  encryptedData:
    DB_PASSWORD: AgAf01F7LhDibdl+uj7EDBuA+JqUzj2QX1ErOxyFd/VOMcAiH9vyZVf3UdWcwwIb8zctjZfI0WJRjDoHJHpt/11pvaE9cJ+/szM0zLjhRMMY6qrlGurXzUoBpQrN0anBEbtv7F1wsEi805b6+eMA3Ggf9obOvnlpICRQKoVpbfRjoWkbIcv/LTYqJPaII/ouoJNoXfvAt1bRzFnuPMqDEUu9wlRVFNNZrGijb/9hMEMK3qmU7u/tzqpLZE76ttE3swTrPjD/se5arIjTYAgSBCqvFFPmThuGgyyXBpGF7wWrluIVUCe8B4R2I4WUf11DRsotXRS8h2IPvVlj/mZC4n2dQhE4qgP2HSVUWq7PQGvV22fulOy+TuX1AiM/Dtt9e7khTEOBhjnpzJG5EFuTdgkmPwZL3pp09s18B3Jl4oJKMY4bDKbelPKe/Vp5KAu9Efspkdnug11E+bFeUcR/L6sDc6vbwUiJWvNKp96nQh8q0CM5Q/EPmQj8x+VbupnjofjDWJ8vGyYLv+YbT1FCZx0aRozpAkrzs9AdSQYYQQCAz4Z8cNbuGl55iZNQ4KWFd8PamEzdd3eCPrTdL6W4d3h1eWU6uSb5yJbpe3WSmeBHwOHW3J9Rpnb/GWV3HLMcYvjDkBUiiJO9cK5h1BghCm4hSsvmsWVEuE4jOjh3Zcu0SAcVi2UbPt9UOOr+weACH84Awv1b8w97lx1Dzkk=
  
    # "houssem-prod"
  
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: voting-prod
    type: Opaque