apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: worker-secret
  namespace: voting-prod

spec:
  encryptedData:
    DB_PASSWORD: AgB4ZibSxHfVT2hKqygReLIVmK52SEfU3k+gMQSIY/L6PiL/EaJb6/KTk/14M5QbaCZbcPa/z7zrMH4hZyFK5b5uH60C26YH53Wcsq4Pcc1U7zYCEYJrQXYzkGkYq7v4ZzzGuNB7AzDgieb+GvaCA0d3Akd7jeqkhUQRIWqnkH/tNoQNHLRXrb/cPeUlSR0d1uJCAuSO5ipbLbqzVAdqo/2+ZiODQVvcPvS754vNiJ6SS/nM4UcqczPPDWJRmq6BAt3kvgnztCbVdznQ5KzK1rGAKygm+T4Z6uSkaBSjfedBYCzizB5nSMwIzzTmuOEb2wC5Q7cSKdl3wV3OimYy3+lZ/Q0Sa9OGal7KR5ukkMmK6YzC+ZpcTUI9Jj+KTk8bzqJWdxM/kPYBAPsCHkMyJ0udXQqoC127c5fmAkyQPpC7bGOYBzOFH1KLundhO8vMdjdxBxpKBsgzomv4fo/l97bi54/9g26SYsrNoZMJUGGzI10gtEPtr1mCKnDtXzw0EvUYQLaXKRInj+I/O0C5AHD1phSgbC1jngITQTpZcd8tp7BPoNYe1IiVXCltWrcNzvrqOHrKe+hT0PE9aKc7RnOgRGJKzrCEcZjYgwkTym3JAVEO3pUsBMXI8hVeLDE7pJK7Knfli9DRuc1jlWwO9zncLWupdj4xCIE9bOQvT4PBKJpTZNcWiDa+l8X/Na7wtuWd+bUwSXajFEu5D2s=
  
    # "houssem-prod"
  
  template:
    metadata:
      creationTimestamp: null
      name: worker-secret
      namespace: voting-prod
    type: Opaque