apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgAK9hoJvHFSvMO5FGu4Uu4Pusw2hqtf7n+iN22D/NK2oTg18SCuWl4G7iv6/3QQOfQdBtnwiXJB/Wv4eM4l3oKTlM6YQM03hPFfwly2LMdfzeC0Hq0FUMhvwGV3Se491FWFc9MX60BTbgZBCKmUQv+jZqhMIvsQRS9btVyDJeiTqv1f/RpazlEhHC/9nrQvhZRiqlVxidb+uRixn9zk6AaoNWkoEisARDIfRghP4a/yr9ImgSJZTr3MBqsKg5kWR91I8XmOtEFJKpXcAWO4Zor1Bj7E5VypgsVDQZvEmH7xh0z4UMfhySO2sj8fM3TmsB3HytQ30dIF5HEXlxoVEWuzoQ0CP7Wc3MFMUzLN+3/CcDhKCyJysOdpdcLEP82d49dG5WzFvUoJ2/joG2MfsJWGgSBAZnugxRczkE2/o7jRWFMevVyWyWvs3k7pxQWZYCjot2Jr+b+qTxBSpqloH2P563TkWt79gT6nTZZ+fSLl91nEwuLPp7tvXybsPNtbGqVe5qX1Wniz+nUR+sxiCi8gyKsy9XhtPFMm+6nfIrcXp5iLF/vBfPJGpSrSIHCqmj0HQUF2PdQDHcQwGiq8S0YGIi10H/Mf6R3iVqcpxjxgPZNJFg64bkrQUHwzGsRtJyW4xgQ15GsW54m2Quq/ZxmzuMfrvSDtcO/+oCY0BRwd9S/0XIw57CQIb4XZDyuurNbzu9Abnw89ypPfTsu1Q1lFXSXKL5AbePYuXLNVNsuha/KvJbetewAByCK+zhoK9nkM2MwZyC41+keUyFvl45rcPUMuFLqUMCv3V6KAdsUMNls=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: monitoring
    type: Opaque