apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: vote-monitor
  namespace: monitoring
  labels:
    release: monitoring

spec:

  namespaceSelector:
    matchNames:
      - voting-prod

  selector:
    matchLabels:
      app: voting-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s