apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: voting-staging

spec:
  encryptedData:
    DB_PASSWORD: AgAxypam5+0c8xus0To8ez8rz5x/v68LRcAlFbkSpFsJWXPj9ucyvP/tFDZOpbjQE0/pII6+V/OrsLwSgZNuAawkSnlqLd05fM7uiYgUR3pMVVLrZLg20pqBJ6p2Ju6k2kxEXrIkF1imD/bDOItC14qNDndUcDDwmmO6lJ20w8qRDIPceJVhF8jB3DAmyjOuOeBMQTJK1j/F+oxVKZCVyZ/VW1jcHqI/Zqk5JUY8w1TCbKupxJPDqsp0+OqG8L88J3rYdk9MR/wOei2xLW4m1pqVeBlLfntugcP7RYmL+0F2wVLVs0NSCnoYGyGQPQ8SFFjA4qL/WWpp4QBsW7rHtTo+5eMYbuLke8ZbzC3bwDt3L9i2BfXzDfwNbsOaU27a2RG7KzNAAlPxkkh1ZiTfBuFHa+8yk9B36KrFHntMILrOXoKuq7PmWpRySloNaMzLzJnDvJIjyruvxIcYaSNmgubKhBFwIWpG9uMnrHHjR8/GL0z2n9MB86CPEzh4JMQW69M++LiTCW30IYFHkEKiJJVLlT2NHnaPJ8AjVdH2/YHR7MZzLzZQk/SMUpNl/kVAULqKOfp6ilB3wMjLREd787ldKf3/L5enPOFPsi2wXCI1datf4HtGC3e9LlCB2RB4g/UIadW+YyGajXSFpdPjM2VjAjBtKapPyMOf9BHu3+NalIzfUWiexXMYtaOKSTW3Yt2GE5YE+tk1HmI4/3pY1VY=
    
    # "houssem-staging"

  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: voting-staging
    type: Opaque