apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: worker-secret
  namespace: voting-staging
spec:
  encryptedData:
    DB_PASSWORD: AgA+2n3QTKJMKqoM0vSiK3Gy8hFVu8dgnUhY6KETKDPNL+8XeIVBBZRMWwrSJEnN3hTuLnrqo0q/pbrDnz/af73nLQ8Xr8dAUiszplMQPL0KPGDTDc71ptDNGTK4TTGpcAAb+jvHPl/5R+WtB2qHfIRI1mAq+mnnbK/0n534iKscrCffUFRhTaM65NVn9/tNSN7HPboow5vC6Y/N/IlLtdVJevqm6sCqnTgPb4YfQc6uZYLDHDgx9pe+vLC/5ses1jllY1hlCxYWGL+qpWPGPhNRRIm5TTahB1joH7vlou5Xb2J5/hT21VaQWJlec3OgQXMCNpwLzMQLCqt9Kz9q5KBiZ29BIY+sWRZw4nj8qUjApC4LesEd9FPfx7G8fOSaPrbaLdecvj77Ajv6vLLh61yazSHyQoN1iTTIXrhMPR2F1cOD9gN1vQLYlecjaQ4laKQQrISQY4Tf5Wg3X+QCIzoJnTVEsrHCtMclbEQpP/DOZNRosvPDtlRymGQ6Qf94XjkfVjlTkzhJFUTSuhF7vqMVYLLqH01pWeg9WJJd1k6w2cBBOZ+vU4H/h8upgYo22niGtEDazeKtHKorReBCtF0LLcroOILRdoXCwNuTOsUZOoccPKd56BJuB0U2tW2X5f7COAO36+LM7o5XZztfPOYwWf0ZfmFjDaKg+jlTEzpqwAgs5aXX0mvQulFsseoEtXTSHAtPjzmdquhk
    # houssem123
  
  template:
    metadata:
      creationTimestamp: null
      name: worker-secret
      namespace: voting-staging
    type: Opaque