apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: worker-secret
  namespace: voting-staging

spec:
  encryptedData:
    DB_PASSWORD: AgBP+MprWht+rxlIsUGAw0/ZH2/Hyop0zEOrsohmuNhAGxtvG9cGezb6+abg9PFhR017QTwrMUkOrygXtmIDHQW+OQl0PALlWenrmkHcWv7NVIDvDPcHsVS4NRXrmIm+HFu35VAGdzyJFbvzokOwrnwrVOyuM2HyZfbbDlSoQ57IKKvx2BpN9j9iJuKZ4ASSst8+o/zpW325DTPXJ5Gjmy/ejBgVv4MRb6vQUhtkYkYBu5HGuR6WoW8WmwP644A/aeWVq2rp1jVcyKOO/SqRbUATaJja392IWLY6gM2CBunSQqaphBXC0oCLeZkZKCta3kz8+EZb2UFX4tF8xOSV+5W5Nj1UMDLBqla2Zy+SnQL43qFDV6e2JIxpgF5h+9H7cK3+fHOuQtBYTG+i5OJ3ChgySyZrZO1BCtH0pWcYTVg4leaxYWP2pjKn/1aj6QDMj/90inZ9MK+W6Fxwre1uj3sbYu2QBLCWZMkKNIzuM7FFMZJAgV3pbEOEVp06W0rPUhQYZiONtqnXZ16me8X31z+1CkVQbzbUG7e5ppnCVdRX1ukKSott6mW+ky5u5D3WVruPx9/3LUbmwxVvPrZDKyQ36zZdPmXnwAWiK6go/1+XOpybBFWJYLiIZijiorFodUSxOj8ncTGfczRnErPtq0CF7eGeofsC+fWNVmso2zlQcCLP6/0PxgCDXlVI3yjreOUI8ZaGZ97LWa958+MTdHg=
  
    # "houssem-staging"
  
  template:
    metadata:
      creationTimestamp: null
      name: worker-secret
      namespace: voting-staging
    type: Opaque