apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: voting-staging
spec:
  encryptedData:
    DB_PASSWORD: AgAVwlni/8xPEKGc1FiXht2mm+z9e+Dk6VmwfsL9oMwCArBjr4VTs9W3QaY/2s+h7OsTBvOGGeMg+25SnuvarQjJBXTtbCvSixSr2fP09Wry2pmRvOzxGb8trjH/hhMADvLgx8LVWhVqcnHdNY2KV6JwXqqDOUjchFxqiR31RuxjwAGeHt04nApKfbwkPhBJYZd1tZFQKL6/Fes0HCRnrPx+ubSZpbSSE4m0YENkCitvci4ZixlAU1TnSJ5cpuNbNgk1Qf4xK4o74MgffW/o667CA5aLXrX71pfro1otkRWTyzeQa+iysI82129jA20/exjoJfUMSSJ7UkyPbXVBagHof2QUTddnojDGvTXBG1Uf37IOe/ND18494LU8vC1JU5DB/IABsdiW4GFuuqfniS+28U7C01WS7Abj43BStTUWY2SWCgdR3w7S+T8Rhqqvz5hHZWjBIs7jJqvuY15nDuJXoDkgWXoZKe/qdOhI1t+V62w/x9wp2G1xO+uVJ4uPgi3QBQk5JeKls0um1RNH8oQT28Fr2J5PqoeI5FhwVy3obgANeUxIAAathTPJxxCoKji7FDsA3XRvTqrKJDBB6H+s9CRqbToIg3Lf6QJZlcx6pL9Ldk8alGtXUHabMRvsWoTKRz3+zJ6d5b3OiswmdF70cU/WspEvK3DEnY+wws6xW3KcYkc0PNW8RVKYKJMDAmoaHAfpdRBIP/a6
    # houssem123
  
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: voting-staging
    type: Opaque