apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: result-secret
  namespace: voting-staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCDdWbjpgQ3DNSHME+OCrhFqdGUd1gPraM8eeR+u2OqukNB35aHD+TT/fPcFPYV2fOKvKV163aR+Es+5AdEuCsUS4tqCc60k9XMo5ZzvLNDKXyrMQQNlUf6aI9sSxspJ42sJn1+HhDahvFZxLr+ztqrAkoEp/9WHhvMaZjBD1z5eunRyHbPgCyd8/9iTNsR+ISuvZHB9PrwTkAmYtKOFC8m2rVJ1mxdROxKpkpIS4rXZ6xdhz/Mx+aNRHCjRatQucPD+m9Vz84QA5bBeXo4bilLxJtSH16e0B/N0eLXvtfoDH6IszrbFtpLTPFwZKU08KdbFp/69aRkliipy3aWWfs8GZL/kxqQ8KmSBQbSiCIBGpOpy2g93+X45OqUJd6OhghfcJ0zi9B0ShTmi3YM5LBikMreOeWULU+C2aSmGv/lVDTEA6+ZJ7g9QpQFWOA8Pr2V/sA21MmPR5q84qdNqr67qqcWPSGKLVKJwqalAZXgqBsAJVmT/jgUi7zu2YObiT0jG2quTLKA8eE+z2xSBp8JETp21ozmQDxgPsfColI9o3D/1iSDG0PMARKvoEfg0zbj4Dp4PdNKP7lo7n3yUXuuSixVlFcis79CIUKARf16TbZc+HNINDYV6dP9Fi5O4L0XQdLrlC35JePzPLXzOzC3AvVQteLVgbVDo0nTEOopM6iX3yBoMvVfIuKGDL1nBKyxD5HPyzPbfGZP
    # houssem123
  
  template:
    metadata:
      creationTimestamp: null
      name: result-secret
      namespace: voting-staging
    type: Opaque