apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: result-secret
  namespace: voting-staging

spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBh67/4/eMUddhCkgJMP3vNO1wmHfPgs2aKzd1tJPnO1RQlhR/GXW4OlZt4RZezfrRHN/V+1+POE24BPTxc0CLuyt7vVOpLz93G/Mu1bYzt1ZCIkntnlKKYZZEjTJi1unskA55Vc94Z7GBdlDgqjz9OX+dNkVc5J/V5cioVIaectmlsqqZLVeSl7p9MH+hxXFRMe5pJ1gJFcbQ/VRRRbmXji6RGXwBPPgUbv2G0xjPLg4qShDLg4CEMe3SuKcikvd/2tpcx3uXdeBzOYBtNZCaSabQy+UoFJycksVZH5rfbwzdpd7SKWPB1ITwzVhePtU18b9vdlUmU32PJR9tzd3ZBri7blHxYT96+uCGDipEg8dZbSv/sbkyzm52yZovJvSeZO0B3NcqKv/z4kClBWtke0Kj++XXdQF7ql1q6w2xfybcm3rc2ZrYNqck5kVTabFXOmxqj01pT7PzVJZY/gZ2BIc2FbHsaYY71HjOgqBJRxtN0i0zFyn1I6E+M2JtRJDHGngqnvEsGRu1xkBXfmQ6bWkI11CvHjS1O3aPMoz4W6fgydAJPSsrrLFGipeesjWQZ+tp30R5vGqPpkcJpBsX4F6KhdYEd3WgHNkX92eX8drn7yAjZzVtZbVyMLSibX3Q6ydAtmGQOgYMcQp09Sb8GDuSv5Dfln4ZJJxZZhLA1kp2eY+MKkQnzhL8ZX1MX5yWosI2bh+Rd9tV+JDtMynA=
  
  # "houssem-staging"
  
  template:
    metadata:
      creationTimestamp: null
      name: result-secret
      namespace: voting-staging
    type: Opaque