apiVersion: v1
kind: Service

metadata:
  name: voting-db
  labels:
    app: postgres-app

spec:
  selector:
    app: postgres-app

  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      
  type: ClusterIP